### ISSUE TITLE
[Bug] No result from testing

### ISSUE THREAD

**Issue by Motzumoto** [dragdev-studios/PostBin#15]
**Describe the bug**
Im running the async function from this repo and im getting no result.

**To Reproduce**
Im running the async function from this repo
```py
import postbin
# Async app
async def main():
    url = await postbin.postAsync(f"FooBar Bazz")
    print(f"Your paste is located at {url}")
```

**Expected behavior**
I should be getting an output, but im getting literally nothing, not even an error
**Screenshots & Tracebacks**
![image](https://user-images.githubusercontent.com/45925152/156587297-57782556-f0be-4138-86ec-b35ea5148e3b.png)

**Package info:**
![image](https://user-images.githubusercontent.com/45925152/156586757-53b6280f-bc17-45ef-9863-065b3d1aa1e5.png)

[ x ] I have checked for open issues regarding this bug
[ x ] I have checked open pull requests for fixes to this issue
[ x ] I have ensured I have updated the module
[ ] I am sure its not me being stupid

**Comment by zanderp25** [comment]
How are you calling this function?

**Comment by Motzumoto** [comment]
> How are you calling this function?

for some reason its working now, nothing changed it just decided to work

**Comment by zanderp25** [comment]
Nice
